# Generated by Django 6.0.2 on 2026-02-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('HSN_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length_ft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_ft', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_type', models.CharField(choices=[('SHEET', 'Per Sheet'), ('SQFT', 'Per Square Feet')], default='SHEET', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_sheets', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=50)),
                ('stock_status', models.CharField(editable=False, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
