# Generated by Django 6.0.2 on 2026-02-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_price',
        ),
    ]
