# Generated by Django 6.0.2 on 2026-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='HSN_code',
            new_name='hsn_code',
        ),
    ]
