# Generated by Django 6.0.2 on 2026-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='new',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
