# Generated by Django 6.0.2 on 2026-02-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='new',
        ),
    ]
