# Generated by Django 6.0.2 on 2026-02-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
    ]
