# Generated by Django 6.0.2 on 2026-02-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_payment_status_alter_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', editable=False, max_length=10),
        ),
    ]
